<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/custom-vocab.css', 'CustomVocab'));
?>

<?php echo $this->pageTitle($translate('Custom Vocabs')); ?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('CustomVocab\Api\Adapter\CustomVocabAdapter', 'create')): ?>
    <?php echo $this->hyperlink($translate('Add new vocab'), $this->url('admin/custom-vocab/add'), ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<?php if (!$vocabs): ?>
<p><?php echo $translate('There are no custom vocabs'); ?></p>
<?php else: ?>
<table>
    <thead>
        <tr>
            <th><?php echo $translate('Label'); ?></th>
            <th><?php echo $translate('Owner'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($vocabs as $vocab): ?>
        <tr>
            <td>
                <ul class="actions">
                    <?php if ($vocab->userIsAllowed('update')): ?>
                    <li><?php echo $vocab->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'aria-label' => $translate('Edit'),
                        'title' => $translate('Edit'),
                    ]); ?></li>
                    <?php endif; ?>
                    <?php if ($vocab->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($vocab->url('delete-confirm')); ?>"
                        class="o-icon-delete sidebar-content"
                        aria-label="<?php echo $escape($translate('Delete')); ?>"
                        title="<?php echo $escape($translate('Delete')); ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?php echo $escape($vocab->url('show-details')); ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?php echo $escape($translate('Details')); ?>"
                        title="<?php echo $escape($translate('Details')); ?>"></a></li>
                </ul>
                <?php echo $escape($vocab->label()); ?></td>
            <td><?php echo $escape($vocab->owner() ? $vocab->owner()->name() : $translate('[Unknown]')); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($translate('Close')); ?>"
        title="<?php echo $escape($translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>
