<?php
$this->headScript()->appendFile($this->assetUrl('js/admin-form.js', 'CustomVocab'));
$translate = $this->plugin('translate');
?>
<?php $form->prepare(); ?>
<?php echo $this->pageTitle($translate('Edit'), 1, $translate('Custom Vocab'), $vocab->label()); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <?php if (in_array($vocab->typeValues(), ['literal', 'uri'])): ?>
    <?php echo $this->hyperlink($translate('Export'), $this->url('admin/custom-vocab/id', ['action' => 'export', 'id' => $vocab->id()]), ['class' => 'button', 'aria-label' => $translate('Export'), 'title' => $translate('Export')]); ?>
    <?php echo $this->hyperlink($translate('Import'), $this->url('admin/custom-vocab/id', ['action' => 'import', 'id' => $vocab->id()]), ['class' => 'button', 'aria-label' => $translate('Import'), 'title' => $translate('Import')]); ?>
    <?php endif; ?>
    <?php echo $this->hyperlink($this->translate('Cancel'), $this->url('admin/custom-vocab', ['action' => 'browse'], true), ['class' => 'button']); ?>
    <button><?php echo $this->escapeHtml($translate('Submit')); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php echo $this->form()->closeTag(); ?>
