<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \CustomVocab\Api\Representation\CustomVocabRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<h2><?= $escape($resource->label()) ?></h2>
<div><?= $escape(sprintf($translate('Language: %s'), $resource->lang() ?: $translate('[none]'))) ?></div>

<?php switch ($resource->typeValues()):
    case 'resource':
        $itemSet = $resource->itemSet();
        ?>
<div><?= sprintf(
    $translate('%1$s in item set %2$s'),
    $hyperlink(sprintf($translate('%d items'), $itemSet->itemCount()), $url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['item_set_id' => $itemSet->id()]])),
    $itemSet->link($itemSet->displayTitle())
) ?>
<?php break;

    case 'uri': ?>
<ul>
    <?php foreach ($resource->listUriLabels() as $uri => $label): ?>
    <li><a href="<?= $escapeAttr($uri) ?>" target="_blank"><?= $escape($label) ?></a></li>
    <?php endforeach; ?>
</ul>
<?php break;

    case 'literal': ?>
<ul>
    <?php foreach ($resource->listTerms() as $term): ?>
    <li><?= $escape($term) ?></li>
    <?php endforeach; ?>
</ul>
<?php break;

    default: ?>
<div class="warning"><?= $translate('This custom vocabulary does not contain any value.') ?></div>

<?php endswitch; ?>
